[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "book-translator-backend"
version = "0.1.0"
description = "Backend for Book Translator"
requires-python = ">=3.11"
dependencies = []
