

services:
  db:
    image: postgres:15-alpine
    container_name: book-translator-db
    environment:
      POSTGRES_DB: books
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d books"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: book-translator-redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  minio:
    image: quay.io/minio/minio:RELEASE.2024-04-18T19-09-19Z
    container_name: book-translator-minio
    command: server /data --console-address :9001
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - minio-data:/data
    ports:
      - "9000:9000"
      - "9001:9001"
    healthcheck:
      test: ["CMD", "mc", "ready", "local"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ..
      dockerfile: infra/Dockerfile.backend
    container_name: book-translator-backend
    env_file:
      - ../backend/.env
    environment:
      DATABASE_URL: postgresql+psycopg://postgres:postgres@db:5432/books
      REDIS_URL: redis://redis:6379/0
      S3_ENDPOINT_URL: http://minio:9000
      S3_REGION: us-east-1
      S3_BUCKET: book-translator
      S3_ACCESS_KEY: minioadmin
      S3_SECRET_KEY: minioadmin
    volumes:
      - ../backend:/app
    working_dir: /app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
      minio:
        condition: service_healthy

  worker:
    build:
      context: ..
      dockerfile: infra/Dockerfile.backend
    container_name: book-translator-worker
    env_file:
      - ../backend/.env
    environment:
      DATABASE_URL: postgresql+psycopg://postgres:postgres@db:5432/books
      REDIS_URL: redis://redis:6379/0
      S3_ENDPOINT_URL: http://minio:9000
      S3_REGION: us-east-1
      S3_BUCKET: book-translator
      S3_ACCESS_KEY: minioadmin
      S3_SECRET_KEY: minioadmin
    volumes:
      - ../backend:/app
    working_dir: /app
    command: celery -A app.workers.celery_app worker --loglevel=info
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
      minio:
        condition: service_healthy
      backend:
        condition: service_started

  frontend:
    build:
      context: ..
      dockerfile: infra/Dockerfile.frontend
    container_name: book-translator-frontend
    environment:
      NEXT_PUBLIC_API_BASE: http://localhost:8000
      CHOKIDAR_USEPOLLING: "true"
    volumes:
      - ../frontend:/app
      - frontend-node-modules:/app/node_modules
    working_dir: /app
    command: npm run dev
    ports:
      - "3000:3000"
    depends_on:
      backend:
        condition: service_started

volumes:
  db-data:
  minio-data:
  frontend-node-modules:
