
services:
  backend:
    build: ../backend
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    env_file:
      - ../.env
    volumes:
      - ../backend:/app
      - ../data:/data
    ports:
      - "8000:8000"
    depends_on:
      - minio

  frontend:
    build:
      context: ../frontend
    depends_on:
      - backend
    environment:
      NEXT_PUBLIC_API_BASE: http://backend:8000
    ports:
      - "3000:3000"

  minio:
    image: minio/minio:latest
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    volumes:
      - ../objectdata:/data
    ports:
      - "9000:9000"
      - "9001:9001"
