version: "3.9"
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: books
    ports: ["5432:5432"]
  redis:
    image: redis:7
    ports: ["6379:6379"]
  minio:
    image: minio/minio:latest
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports: ["9000:9000", "9001:9001"]
    volumes:
      - minio-data:/data
  backend:
    build:
      context: ../backend
      dockerfile: ../infra/Dockerfile.backend
    env_file: ../backend/.env
    depends_on: [db, redis, minio]
    ports: ["8000:8000"]
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
  worker:
    build:
      context: ../backend
      dockerfile: ../infra/Dockerfile.backend
    env_file: ../backend/.env
    depends_on: [backend, db, redis, minio]
    command: celery -A app.workers.celery_app.celery worker --loglevel=INFO --concurrency=2
  frontend:
    build:
      context: ../frontend
      dockerfile: ../infra/Dockerfile.frontend
    environment:
      NEXT_PUBLIC_API_BASE: http://localhost:8000
    ports: ["3000:3000"]
volumes:
  minio-data:
